### ISSUE TITLE
Problem with directory separator DS

### ISSUE THREAD

**Issue by vsjov** [PeterMacej/contactform_enh#1]
I have fixed the problem Joomla v3.6.2 was reporting for `DS` in this plugin v1.0.4

Open `contactformenhancer.php`

after `defined('_JEXEC') or die;`
add `if(!defined('DS')) define('DS', DIRECTORY_SEPARATOR);`

**Comment by PeterMacej** [comment]
Thank you. I wasn't aware of this problem, probably another plugin has defined the DS on my site. I fixed it and created a new version. I completely removed the usage of DS and I use DIRECTORY_SEPARATOR now. Please try it and let me know.

**Comment by vsjov** [comment]
You're welcome. 

v1.0.5 works as expected. All is ok.
